### ISSUE TITLE
[GENERAL] Can't pass "Attiva le notifiche di esposizione COVID-19" screen

### ISSUE THREAD

**Issue by esQmo** [immuni-app/immuni-app-android#118] opened 2020-05-30 01:17 UTC
Just build the project then installed on device. Can't pass the onboardig screen, in the step **Attiva le notifiche di esposizione COVID-19**. Touching Consenti doesn't go further but displays a toast message with "Notifiche di espozicione non attiva". 
What I understood is that I need to activate some settings but can't figure it out. GPS and Bluetooth are enabled.

**Comment by Talebian12** [comment] 2020-05-30 01:22
From the README:
`Please note that Google restricts the usage of the Exposure Notification API to government entities or developers approved by a government entity to develop an application on behalf of a government for COVID-19 response efforts. Full details are in the Additional Terms document. Otherwise, you may build and use the application, but you will not be able to use the underlying Exposure Notification system.`

**Comment by esQmo** [comment] 2020-05-30 01:31
Well, I read that line, but can't really get it when they say "... you may build and use the application, .. " So it means I can just build, then deploy to the device to get stuck in there? Or I can browse the apps but won't be able to detect other devices around

**Comment by Talebian12** [comment] 2020-05-30 01:34
> Well, I read that line, but can't really get it when they say "... you may build and use the application, .. " So it means I can just build, then deploy to the device to get stuck in there? Or I can browse the apps but won't be able to detect other devices around

See: #21

**Comment by esQmo** [comment] 2020-05-30 01:40
Hehe, I meant besides going to the code and making some modifications

**Comment by esQmo** [comment] 2020-05-30 02:34
For those who will face the same issue, just modify a line incode: 
In `ExposureNotificationManager`, line 98, change ` _isBroadcastingActive.value = it` to ` _isBroadcastingActive.value = true`. Will bypass the activation screen.

**Comment by mlocati** [comment] 2020-05-30 06:39
Any reason to keep this open?

**Comment by marcouberti** [comment] 2020-05-30 06:50
I close this issue since this is the intended behaviour.

**Closed by marcouberti** 2020-05-30 06:50 UTC
Labels: triage
