### ISSUE TITLE
[FEAT] Notify when something goes wrong and the tracing service stops.

### ISSUE THREAD

**Issue by carlidel** [immuni-app/immuni-app-android#175] opened 2020-06-04 08:09 UTC
**Is your feature request related to a problem? Please describe it.**
As I have experienced in another (now somewhat solved) issue (#157), it might happen that the tracking service just stops working without any warnings or notifications.

Right now, the only way a user can now if the service has stopped working is to open the app from time to time and check its status (it's even written inside the app: "Apri periodicamente Immuni per verificarne lo stato").

This is not ideal if what we want is a "Set It And Forget It" system!

**Describe the solution you'd like**
A notification banner that appears if and when the Exposure Notification service (or any other part of the app) stops working for whatever reason.

If that is already implemented and I have missed it, than some more clarity in the settings zones on which notifications the app can show to you.

**Comment by bfabio** [comment] 2020-06-04 11:50
Duplicate of #106, it should be fixed now.

**Closed** 2020-06-04 11:58 UTC
Labels: triage
