### ISSUE TITLE
BUG - on bluetooth active

### ISSUE THREAD

**Issue by davidevaccarini** [immuni-app/immuni-app-android#160] opened 2020-06-02 13:22 UTC
if you have bluetooth activated, the app go on loop and can't accept the notifier...you must turn off the bluetooth and can accept the notifier (now the bluetooth go up and notifier is ok)

**Comment by davidevaccarini** [comment] 2020-06-02 13:23
this on HONOR 10 whit andorid 9

**Comment by immuniopensource** [comment] 2020-06-03 15:53
Thanks @davidevaccarini for this issue. Since this is a duplicate of #146 I am closing this to continue the discussion over there. Thanks again for your time!

**Closed** 2020-06-03 15:53 UTC
Labels: triage
