### ISSUE TITLE
[FEAT] Explains why is needed geolocation

### ISSUE THREAD

**Issue by MFranceschi6** [immuni-app/immuni-app-android#166] opened 2020-06-03 10:41 UTC
**Is your feature request related to a problem? Please describe it.**
Looking into the review section of the PlayStore It clear that exists a misunderstanding between geolocation and GPS. I think it's necessary to explain it

**Describe the solution you'd like**
I suggest to add a section in the FAQ and the onboarding phase where it's explained the necessity to use geolocation and the fact that this doesn't mean using the GPS.

**Additional context**
Just a few of the reviews I'm talking about
![Screenshot_20200603-123047~2](https://user-images.githubusercontent.com/9447889/83627589-75030b80-a597-11ea-83dd-3eb371291660.jpg)
![Screenshot_20200603-123121~2](https://user-images.githubusercontent.com/9447889/83627594-759ba200-a597-11ea-90a7-4fd5d15f21ac.jpg)
![Screenshot_20200603-123009~2](https://user-images.githubusercontent.com/9447889/83627595-76343880-a597-11ea-8727-9f5aff27786a.jpg)
![Screenshot_20200603-123036~2](https://user-images.githubusercontent.com/9447889/83627597-76343880-a597-11ea-8f3b-d72689c9f03a.jpg)

**Comment by Talebian12** [comment] 2020-06-03 10:51
> **Is your feature request related to a problem? Please describe it.**
> Looking into the review section of the PlayStore It clear that exists a misunderstanding between geolocation and GPS. I think it's necessary to explain it
> 
> **Describe the solution you'd like**
> I suggest to add a section in the FAQ and the onboarding phase where it's explained the necessity to use geolocation and the fact that this doesn't mean using the GPS.
> 
> **Additional context**
> Just a few of the reviews I'm talking about
> ![Screenshot_20200603-123047~2](https://user-images.githubusercontent.com/9447889/83627589-75030b80-a597-11ea-83dd-3eb371291660.jpg)
> ![Screenshot_20200603-123121~2](https://user-images.githubusercontent.com/9447889/83627594-759ba200-a597-11ea-90a7-4fd5d15f21ac.jpg)
> ![Screenshot_20200603-123009~2](https://user-images.githubusercontent.com/9447889/83627595-76343880-a597-11ea-8727-9f5aff27786a.jpg)
> ![Screenshot_20200603-123036~2](https://user-images.githubusercontent.com/9447889/83627597-76343880-a597-11ea-8f3b-d72689c9f03a.jpg)

Questo sistema di tracciamentop contatti utilizza Bluetooth Low Energy (BLE), il quale secondo la documentazione di Android (Documentazione Bluetooth LE Scanning [qui](https://source.android.com/devices/bluetooth/ble#location-scanning)) richiede obbligatoriamente l'attivazione della localizzazione per l'utilizzo dello scanning BLE. Comunque Immuni anche se richiede l'attivazione della localizzazione non implica l'uso del modulo GPS, essendo che per l'utilizzo è richiesto il permesso [ACCESS_FINE_LOCATION](https://developer.android.com/reference/android/Manifest.permission#ACCESS_FINE_LOCATION), ma nel Manifest è richiesto solo il permesso [BLUETOOTH](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH).

**Comment by MFranceschi6** [comment] 2020-06-03 10:58
Siamo d'accordo, infatti suggerisco di aggiungerlo all'app con parole semplici (parte più difficile) per persone non addette ai lavori.

Mi scuso se dalla issue sembrava che chiedessi una spiegazione

**Comment by bfabio** [comment] 2020-06-03 11:29
@MFranceschi6 See #149

**Comment by immuniopensource** [comment] 2020-06-03 15:39
Duplicate of #149. Closing, thanks!

**Closed by immuniopensource** 2020-06-03 15:39 UTC
Labels: triage
