### ISSUE TITLE
[BUG] Notification about reactivate Immuni doesn't disappear even if Immuni is active again

### ISSUE THREAD

**Issue by mariaclaudia** [immuni-app/immuni-app-android#221] opened 2020-06-15 16:51 UTC
**Describe the bug**

Even if IMMUNI is reactivated, it is not possible to close the previous notification about the service that was inactive (please, see the screenshot attached)

**To Reproduce**

1. Turn your phone in Airplane mode or disable Bluetooth
2. Disable Airplane mode or enable Bluetooth, a notification (please, see the screenshot attached) will be pushed to your mobile phone 
3. Reactivate Immuni

**Expected behaviour**

The notification should disappear or at least it should be possible to close/remove it.
However, the notification remains displayed even clicking the notification

**Screenshots**

![Screenshot_20200615-181458_2](https://user-images.githubusercontent.com/1733135/84684239-b05aee00-af38-11ea-9b65-4e87d74f15c0.png)

**Smartphone (please complete the following information):**

- Device: Mi A2 Lite 
- OS: Android version: 10
- Build number: QKQ1.191002.002.V11.0.5.0.QDLMIXM

**Comment by lmasellis** [comment] 2020-06-16 18:51
Duplicate of #204

**Comment by immuniteam** [comment] 2020-06-26 07:59
Please see the issue #204 containing an update on this bug. In the meanwhile I am closing this issue since it's a duplicate, thanks for your patience!

**Closed by immuniteam** 2020-06-26 07:59 UTC
Labels: duplicate
