### ISSUE TITLE
[FEAT] Enable green pass download for foreign vaccinated

### ISSUE THREAD

**Issue by raphaelbussa** [immuni-app/immuni-app-android#375] opened 2022-01-02 21:45 UTC
**Is your feature request related to a problem? Please describe it.**
Foreign vaccinated that had validated their vaccination in Italy, can't download the green pass inside the immuni app

**Describe the solution you'd like**
Add an option to download the green pass

**Describe alternatives you've considered**
Add the pass scanning the green pass QR code

**Comment by tiziodcaio** [comment] 2022-01-05 11:04
Duplicate of #355

**Closed** 2022-01-05 12:53 UTC

**Comment by raphaelbussa** [comment] 2022-01-19 10:44
Not exactly a duplicate, right now on the form to download the pass, there is only the option to retrieve the certificate using the health card.
If you are vaccinated in a foreign country, you have to use your document number to get the pass, and the form doesn't allow you to do that.

![Screenshot 2022-01-19 at 10 41 13](https://user-images.githubusercontent.com/3964819/150114815-9c6d43e4-9da9-4fd6-a8f3-965731e94f52.png)
